package com.zpmc.ztos.infra.base.business.enums.argo;

import org.apache.commons.lang.enums.EnumUtils;

import java.util.EnumSet;
import java.util.List;

public enum BusEventTypeEnum {
    DB_EVENT_GROUP_CLOSED(1, "DB_EVENT_GROUP_CLOSED", "", "", "DB_EVENT_GROUP_CLOSED"),
    DB_ENTITY_CREATED(2, "DB_ENTITY_CREATED", "数据库实体创建事件", "", "DB_ENTITY_CREATED"),
    DB_ENTITY_UPDATED(3, "DB_ENTITY_UPDATED", "数据库实体更新事件", "", "DB_ENTITY_UPDATED"),
    DB_ENTITY_DELETED(4, "DB_ENTITY_DELETED", "数据库实体删除事件", "", "DB_ENTITY_DELETED"),
    CTL_UPDATE_JOB_STEP_PROJECTION(5, "CTL_UPDATE_JOB_STEP_PROJECTION", "控制更新job步骤更新事件", "", "CTL_UPDATE_JOB_STEP_PROJECTION"),
    ECI_EXPEDITE_WORKASSIGNMENT(6, "ECI_EXPEDITE_WORKASSIGNMENT", "加快工作指派事件", "", "ECI_EXPEDITE_WORKASSIGNMENT"),
    ECI_ASC_STATUS_UPDATED(7, "ECI_ASC_STATUS_UPDATED", "asc状态更新事件", "", "ECI_ASC_STATUS_UPDATED"),
    ECI_ASC_ORDER_ENTERED(8, "ECI_ASC_ORDER_ENTERED", "asc命令输入事件", "", "ECI_ASC_ORDER_ENTERED"),
    ECI_ASC_ORDER_ACCEPTED(9, "ECI_ASC_ORDER_ACCEPTED", "asc命令接受事件", "", "ECI_ASC_ORDER_ACCEPTED"),
    ECI_ASC_CONTAINER_LIFTED(10, "ECI_ASC_CONTAINER_LIFTED", "asc集装箱抬起事件", "", "ECI_ASC_CONTAINER_LIFTED"),
    ECI_ASC_CONTAINER_LANDED(11, "ECI_ASC_CONTAINER_LANDED", "asc集装箱放下事件", "", "ECI_ASC_CONTAINER_LANDED"),
    ECI_ASC_ORDER_COMPLETED(12, "ECI_ASC_ORDER_COMPLETED", "asc命令完成事件", "", "ECI_ASC_ORDER_COMPLETED"),
    ECI_ASC_ORDER_CANCEL_ACCEPTED(13, "ECI_ASC_ORDER_CANCEL_ACCEPTED", "asc命令取消被接受事件", "", "ECI_ASC_ORDER_CANCEL_ACCEPTED"),
    ECI_ASC_ORDER_REJECTED(14, "ECI_ASC_ORDER_REJECTED", "asc命令完成拒绝事件", "", "ECI_ASC_ORDER_REJECTED"),
    ECI_ASC_AT_TRANSFER_ZONE(15, "ECI_ASC_AT_TRANSFER_ZONE", "asc在转换区", "", "ECI_ASC_AT_TRANSFER_ZONE"),
    ECI_ASC_ORDER_ABORTED(16, "ECI_ASC_ORDER_ABORTED", "asc命令中止", "", "ECI_ASC_ORDER_ABORTED"),
    ECI_ASC_UNORDERED_ENTERED(17, "ECI_ASC_UNORDERED_ENTERED", "asc无命令进入", "", "ECI_ASC_UNORDERED_ENTERED"),
    ECI_ASC_ORDER_PROGRESS_UPDATED(18, "ECI_ASC_ORDER_PROGRESS_UPDATED", "asc命令中进度更新", "", "ECI_ASC_ORDER_PROGRESS_UPDATED"),
    ECI_ASC_ORDER_MAINTENANCE(19, "ECI_ASC_ORDER_MAINTENANCE", "asc命令维护", "", "ECI_ASC_ORDER_MAINTENANCE"),
    ECI_ASC_UNAVAILABLE(20, "ECI_ASC_UNAVAILABLE", "asc不可用", "", "ECI_ASC_UNAVAILABLE"),
    ECI_AGV_STATUS_UPDATED(21, "ECI_AGV_STATUS_UPDATED", "agv状态更新", "", "ECI_AGV_STATUS_UPDATED"),
    ECI_AGV_ORDER_ENTERED(22, "ECI_AGV_ORDER_ENTERED", "agv命令输入", "", "ECI_AGV_ORDER_ENTERED"),
    ECI_AGV_ORDER_ACCEPTED(23, "ECI_AGV_ORDER_ACCEPTED", "agv命令接受", "", "ECI_AGV_ORDER_ACCEPTED"),
    ECI_AGV_AT_DESTINATION(24, "ECI_AGV_AT_DESTINATION", "agv到达目的地", "", "ECI_AGV_AT_DESTINATION"),
    ECI_AGV_ORDER_COMPLETED(25, "ECI_AGV_ORDER_COMPLETED", "agv命令完成", "", "ECI_AGV_ORDER_COMPLETED"),
    ECI_AGV_ORDER_CANCEL_ACCEPTED(26, "ECI_AGV_ORDER_CANCEL_ACCEPTED", "agv命令取消被接受", "", "ECI_AGV_ORDER_CANCEL_ACCEPTED"),
    ECI_AGV_ORDER_REJECTED(27, "ECI_AGV_ORDER_REJECTED", "agv命令拒绝", "", "ECI_AGV_ORDER_REJECTED"),
    ECI_AGV_ORDER_ABORTED(28, "ECI_AGV_ORDER_ABORTED", "agv命令中止", "", "ECI_AGV_ORDER_ABORTED"),
    ECI_AGV_ORDER_PROGRESS_UPDATED(29, "ECI_AGV_ORDER_PROGRESS_UPDATED", "agv命令进度更新", "", "ECI_AGV_ORDER_PROGRESS_UPDATED"),
    ECI_AGV_EXITED_ORIGIN(30, "ECI_AGV_EXITED_ORIGIN", "agv退出原点", "", "ECI_AGV_EXITED_ORIGIN"),
    ECI_AGV_PBUFFER_ENTERED(31, "ECI_AGV_PBUFFER_ENTERED", "agv进去pb", "", "ECI_AGV_PBUFFER_ENTERED"),
    ECI_AGV_PBUFFER_EXITED(32, "ECI_AGV_PBUFFER_EXITED", "agv退出pb", "", "ECI_AGV_PBUFFER_EXITED"),
    ECI_AGV_BATTERY_STATE_UPDATED(33, "ECI_AGV_BATTERY_STATE_UPDATED", "agv电池状态更新", "", "ECI_AGV_BATTERY_STATE_UPDATED"),
    ECI_AGV_ORDER_COMPLETION_DELAYED(34, "ECI_AGV_ORDER_COMPLETION_DELAYED", "agv命令完成延迟", "", "ECI_AGV_ORDER_COMPLETION_DELAYED"),
    ECI_ASH_LIFT_TARGET_LOCKED(35, "ECI_ASH_LIFT_TARGET_LOCKED", "ash起升目标锁定", "", "ECI_ASH_LIFT_TARGET_LOCKED"),
    ECI_ASH_CONTAINER_LIFTED(36, "ECI_ASH_CONTAINER_LIFTED", "ash集装箱抬起", "", "ECI_ASH_CONTAINER_LIFTED"),
    ECI_ASH_CONTAINER_GROUNDED(37, "ECI_ASH_CONTAINER_GROUNDED", "ash集装箱落地", "", "ECI_ASH_CONTAINER_GROUNDED"),
    ECI_ASH_PNR_PASSED(38, "ECI_ASH_PNR_PASSED", "ash pnr通过", "", "ECI_ASH_PNR_PASSED"),
    ECI_ASH_ENERGY_STATE_UPDATED(39, "ECI_ASH_ENERGY_STATE_UPDATED", "ash能耗状态更新", "", "ECI_ASH_ENERGY_STATE_UPDATED"),
    ECI_AHT_UNORDERED_ENTERED(40, "ECI_AHT_UNORDERED_ENTERED", "aht无命令进入", "", "ECI_AHT_UNORDERED_ENTERED"),
    ECI_AHT_UNAVAILABLE(41, "ECI_AHT_UNAVAILABLE", "aht不可用", "", "ECI_AHT_UNAVAILABLE"),
    ECI_QC_STATUS_UPDATED(42, "ECI_QC_STATUS_UPDATED", "qc状态更新", "", "ECI_QC_STATUS_UPDATED"),
    ECI_QC_ORDER_ENTERED(43, "ECI_QC_ORDER_ENTERED", "qc命令输入", "", "ECI_QC_ORDER_ENTERED"),
    ECI_QC_ORDER_ACCEPTED(44, "ECI_QC_ORDER_ACCEPTED", "qc命令接受", "", "ECI_QC_ORDER_ACCEPTED"),
    ECI_QC_ORDER_COMPLETED(45, "ECI_QC_ORDER_COMPLETED", "qc命令完成", "", "ECI_QC_ORDER_COMPLETED"),
    ECI_QC_UNIDENTIFIED_HANDLED(46, "ECI_QC_UNIDENTIFIED_HANDLED", "qc未定义的处理", "", "ECI_QC_UNIDENTIFIED_HANDLED"),
    ECI_QC_CONTAINER_HANDLED(47, "ECI_QC_CONTAINER_HANDLED", "qc集装箱处理", "", "ECI_QC_CONTAINER_HANDLED"),
    ECI_QC_UNASSIGNED_IDENTIFIED(48, "ECI_QC_UNASSIGNED_IDENTIFIED", "qc未指派未识别", "", "ECI_QC_UNASSIGNED_IDENTIFIED"),
    ECI_QC_CONTAINER_IDENTIFIED(49, "ECI_QC_CONTAINER_IDENTIFIED", "qc集装箱识别", "", "ECI_QC_CONTAINER_IDENTIFIED"),
    ECI_QC_CONTAINER_IMAGE_CAPTURED(50, "ECI_QC_CONTAINER_IMAGE_CAPTURED", "qc集装箱图像捕获", "", "ECI_QC_CONTAINER_IMAGE_CAPTURED"),
    ECI_QC_UNASSIGNED_IMAGE_CAPTURED(51, "ECI_QC_UNASSIGNED_IMAGE_CAPTURED", "qc未指派图像捕获", "", "ECI_QC_UNASSIGNED_IMAGE_CAPTURED"),
    ECI_QC_CONTAINER_MISIDENTIFIED(52, "ECI_QC_CONTAINER_MISIDENTIFIED", "qc集装箱识别错误", "", "ECI_QC_CONTAINER_MISIDENTIFIED"),
    ECI_QC_UNASSIGNED_MISIDENTIFIED(53, "ECI_QC_UNASSIGNED_MISIDENTIFIED", "qc未指派识别错误", "", "ECI_QC_UNASSIGNED_MISIDENTIFIED"),
    ECI_QC_CONTAINER_UPDATED(54, "ECI_QC_CONTAINER_UPDATED", "qc集装箱更新", "", "ECI_QC_CONTAINER_UPDATED"),
    ECI_QC_UNASSIGNED_UPDATED(55, "ECI_QC_UNASSIGNED_UPDATED", "qc未指派更新", "", "ECI_QC_UNASSIGNED_UPDATED"),
    ECI_QC_TRANSFER_READY(56, "ECI_QC_TRANSFER_READY", "qc传输准备", "", "ECI_QC_TRANSFER_READY"),
    ECI_QC_ORDER_PROGRESS_UPDATED(57, "ECI_QC_ORDER_PROGRESS_UPDATED", "qc命令流程更新", "", "ECI_QC_ORDER_PROGRESS_UPDATED"),
    ECI_CONTAINER_POSITION_UPDATED(58, "ECI_CONTAINER_POSITION_UPDATED", "集装箱位置更新", "", "ECI_CONTAINER_POSITION_UPDATED"),
    ECI_UNIT_POSITION_UPDATED(59, "ECI_UNIT_POSITION_UPDATED", "单元位置更新", "", "ECI_UNIT_POSITION_UPDATED"),
    ECI_ECSUPDATE_ACKNOWLEDGED(60, "ECI_ECSUPDATE_ACKNOWLEDGED", "ecs更新反馈", "", "ECI_ECSUPDATE_ACKNOWLEDGED"),
    ECI_CHE_RESET(61, "ECI_CHE_RESET", "che重置", "", "ECI_CHE_RESET"),
    ECI_CHE_HARD_RESET(62, "ECI_CHE_HARD_RESET", "che硬重置", "", "ECI_CHE_HARD_RESET"),
    ECI_CHE_ACTUAL_ECI_POSITION(63, "ECI_CHE_ACTUAL_ECI_POSITION", "che实际设备位置", "", "ECI_CHE_ACTUAL_ECI_POSITION"),
    ECI_AREA_STATUS_UPDATED(64, "ECI_AREA_STATUS_UPDATED", "区域状态更新", "", "ECI_AREA_STATUS_UPDATED"),
    ECI_TRANSFER_POINT_STATUS_UPDATED(65, "ECI_TRANSFER_POINT_STATUS_UPDATED", "tp状态更新", "", "ECI_TRANSFER_POINT_STATUS_UPDATED"),
    ECI_DRIVE_TIME_UPDATED(66, "ECI_DRIVE_TIME_UPDATED", "驾驶时间更新", "", "ECI_DRIVE_TIME_UPDATED"),
    ECI_DYNAMIC_DRIVE_TIME_UPDATED(67, "ECI_DYNAMIC_DRIVE_TIME_UPDATED", "动态驾驶时间更新", "", "ECI_DYNAMIC_DRIVE_TIME_UPDATED"),
    ECI_WQ_BUFFER_STATUS_UPDATED(68, "ECI_WQ_BUFFER_STATUS_UPDATED", "wq缓存状态更新", "", "ECI_WQ_BUFFER_STATUS_UPDATED"),
    ECI_ECS_APPLICATION_STATUS(69, "ECI_ECS_APPLICATION_STATUS", "ecs应用状态", "", "ECI_ECS_APPLICATION_STATUS"),
    LIVE_DATA_CACHE_INSERT(70, "LIVE_DATA_CACHE_INSERT", "实时数据缓存插入", "", "LIVE_DATA_CACHE_INSERT");
    private final int key;
    private final String code;
    private final String desc;
    private final String color;
    private final String displayName;

    BusEventTypeEnum(int key, String code, String desc, String color, String displayName) {
        this.key = key;
        this.code = code;
        this.desc = desc;
        this.color = color;
        this.displayName = displayName;
    }

    public static List getEnumList() {
        return EnumUtils.getEnumList(BusEventTypeEnum.class);
    }

    public static EnumSet getEnumSet() {
        return EnumSet.allOf(BusEventTypeEnum.class);
    }

    public int getKey() {
        return key;
    }

    public String getCode() {
        return code;
    }

    public String getDesc() {
        return desc;
    }

    public String getColor() {
        return color;
    }

    public String getDisplayName() {
        return displayName;
    }

}