package com.zpmc.ztos.infra.base.business.interfaces;

import com.zpmc.ztos.infra.base.common.model.PropertyKeyFactory;

public interface ISecurityPropertyKeys {
    public static final IPropertyKey SECURITY__AUTHENTICATION_FAILURE = PropertyKeyFactory.valueOf("SECURITY__AUTHENTICATION_FAILURE");
    public static final IPropertyKey SECURITY__USER_INACTIVE = PropertyKeyFactory.valueOf("SECURITY__USER_INACTIVE");
    public static final IPropertyKey SECURITY__USER_LOCKED = PropertyKeyFactory.valueOf("SECURITY__USER_LOCKED");
    public static final IPropertyKey SECURITY__EXTERNAL_AUTHENTICATION_FAILURE = PropertyKeyFactory.valueOf("SECURITY__EXTERNAL_AUTHENTICATION_FAILURE");
    public static final IPropertyKey SECURITY__USER_NOT_IN_SYSTEM = PropertyKeyFactory.valueOf("SECURITY__USER_NOT_IN_SYSTEM");
    public static final IPropertyKey SECURITY__INVALID_UID_FORMAT = PropertyKeyFactory.valueOf("SECURITY__INVALID_UID_FORMAT");
    public static final IPropertyKey SECURITY__DUPLICATE_UID = PropertyKeyFactory.valueOf("SECURITY__DUPLICATE_UID");
    public static final IPropertyKey SECURITY__DUPLICATE_ORGANIZATION = PropertyKeyFactory.valueOf("SECURITY__DUPLICATE_ORGANIZATION");
    public static final IPropertyKey SECURITY__ORG_FAILURE = PropertyKeyFactory.valueOf("SECURITY__ORG_FAILURE");
    public static final IPropertyKey SECURITY__ORG_DELETE_FAILURE = PropertyKeyFactory.valueOf("SECURITY__ORG_DELETE_FAILURE");
    public static final IPropertyKey SECURITY__PASSWORD_MISMATCH = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_MISMATCH");
    public static final IPropertyKey SECURITY__CANT_FIND_SECURITY_MANAGER = PropertyKeyFactory.valueOf("SECURITY__CANT_FIND_SECURITY_MANAGER");
    public static final IPropertyKey SECURITY__DUPLICATE_ORGANIZATION_FOR_COUNTRY = PropertyKeyFactory.valueOf("SECURITY__DUPLICATE_ORGANIZATION_FOR_COUNTRY");
    public static final IPropertyKey SECURITY__PASSWORD_LENGTH_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_LENGTH_VIOLATION");
    public static final IPropertyKey SECURITY__PASSWORD_LOWER_CASE_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_LOWER_CASE_VIOLATION");
    public static final IPropertyKey SECURITY__PASSWORD_UPPER_CASE_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_UPPER_CASE_VIOLATION");
    public static final IPropertyKey SECURITY__PASSWORD_NUMERIC_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_NUMERIC_VIOLATION");
    public static final IPropertyKey SECURITY__PASSWORD_SPECIAL_CHARS_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_SPECIAL_CHARS_VIOLATION");
    public static final IPropertyKey SECURITY__PASSWORD_DOES_NOT_MATCH_OLD_PASSWORD = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_DOES_NOT_MATCH_OLD_PASSWORD");
    public static final IPropertyKey SECURITY__PASSWORD_ENTRY_MISSING = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_ENTRY_MISSING");
    public static final IPropertyKey SECURITY__EXPIRED_PASSWORD_CONTINUE_TO_LOGIN = PropertyKeyFactory.valueOf("SECURITY__EXPIRED_PASSWORD_CONTINUE_TO_LOGIN");
    public static final IPropertyKey SECURITY__PASSWORD_MISSING_CURRENT_PASSWORD = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_MISSING_CURRENT_PASSWORD");
    public static final IPropertyKey SECURITY__RETYPED_PASSWORD_MISMATCH = PropertyKeyFactory.valueOf("SECURITY__RETYPED_PASSWORD_MISMATCH");
    public static final IPropertyKey SECURITY__ACCOUNT_WILL_BE_AUTOMATIC_UNLOCKED = PropertyKeyFactory.valueOf("SECURITY__ACCOUNT_WILL_BE_AUTOMATIC_UNLOCKED");
    public static final IPropertyKey SECURITY__ACCOUNT_WILL_BE_LOCKED_WARNING = PropertyKeyFactory.valueOf("SECURITY__ACCOUNT_WILL_BE_LOCKED_WARNING");
    public static final IPropertyKey SECURITY__PASSWORD_RECYCLE_NOT_ALLOWED = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_RECYCLE_NOT_ALLOWED");
    public static final IPropertyKey SECURITY__PASSWORD_EXPIRED = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_EXPIRED");
    public static final IPropertyKey SECURITY__EXTERNAL_AUTH_PASSWORD_EXPIRED = PropertyKeyFactory.valueOf("SECURITY__EXTERNAL_AUTH_PASSWORD_EXPIRED");
    public static final IPropertyKey SECURITY__ACCOUNT_EXPIRED = PropertyKeyFactory.valueOf("SECURITY__ACCOUNT_EXPIRED");
    public static final IPropertyKey SECURITY__ACCOUNT_EXPIRED_AND_SUGGEST_UPDATE = PropertyKeyFactory.valueOf("SECURITY__ACCOUNT_EXPIRED_AND_SUGGEST_UPDATE");
    public static final IPropertyKey SECURITY__PASSWORD_EXPIRY_WARNING = PropertyKeyFactory.valueOf("SECURITY__PASSWORD_EXPIRY_WARNING");
    public static final IPropertyKey SECURITY__SCOPE_COORDINATES_ACCESS_DENITED = PropertyKeyFactory.valueOf("SECURITY__SCOPE_COORDINATES_ACCESS_DENITED");
    public static final IPropertyKey SECURITY__LDAP_PROVIDERS_XML_FILE_LOAD_FAILED = PropertyKeyFactory.valueOf("SECURITY__LDAP_PROVIDERS_XML_FILE_LOAD_FAILED");
    public static final IPropertyKey SECURITY__LDAP_PROVIDERS_XML_LOAD_FAILED = PropertyKeyFactory.valueOf("SECURITY__LDAP_PROVIDERS_XML_LOAD_FAILED");
    public static final IPropertyKey SECURITY__LDAP_PROVIDERS_REMOVE_FAILED = PropertyKeyFactory.valueOf("SECURITY__LDAP_PROVIDERS_REMOVE_FAILED");
    public static final IPropertyKey SECURITY__LDAP_PROVIDERS_XML_PARSE_ERROR = PropertyKeyFactory.valueOf("SECURITY__LDAP_PROVIDERS_XML_PARSE_ERROR");
    public static final IPropertyKey SECURITY__LDAP_BASE_AUTHENT_PROBLEM = PropertyKeyFactory.valueOf("SECURITY__LDAP_BASE_AUTHENT_PROBLEM");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_ACCOUNT_NOT_FOUND = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_ACCOUNT_NOT_FOUND");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_BAD_CREDENTIAL = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_BAD_CREDENTIAL");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_LOGIN_TIME_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_LOGIN_TIME_VIOLATION");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_HOST_RESTRICTION_VIOLATION = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_HOST_RESTRICTION_VIOLATION");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_PASS_EXPIRED = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_PASS_EXPIRED");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_ACCOUNT_DISABLED = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_ACCOUNT_DISABLED");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_ACCOUNT_EXPIRED = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_ACCOUNT_EXPIRED");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_MUST_RESET_PASS = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_MUST_RESET_PASS");
    public static final IPropertyKey SECURITY__LDAP_SEARCH_ACCOUNT_LOCKED = PropertyKeyFactory.valueOf("SECURITY__LDAP_SEARCH_ACCOUNT_LOCKED");
    public static final IPropertyKey SECURITY__LDAP_COMMUNICATION_PROBLEM = PropertyKeyFactory.valueOf("SECURITY__LDAP_COMMUNICATION_PROBLEM");
    public static final IPropertyKey SECURITY__AUTH_PROVIDERS_LIST_EMPTY = PropertyKeyFactory.valueOf("SECURITY__AUTH_PROVIDERS_LIST_EMPTY");
    public static final IPropertyKey SECURITY__SYMM_CRYPTO_SIGNATURE_TOKEN = PropertyKeyFactory.valueOf("SECURITY__SYMM_CRYPTO_SIGNATURE_TOKEN");
    public static final IPropertyKey SECURITY__SYMM_CRYPTO_DECRYPT_FAILED = PropertyKeyFactory.valueOf("SECURITY__SYMM_CRYPTO_DECRYPT_FAILED");
    public static final IPropertyKey SECURITY__SYMM_CRYPTO_MGR_INIT_FAILED = PropertyKeyFactory.valueOf("SECURITY__SYMM_CRYPTO_MGR_INIT_FAILED");
    public static final IPropertyKey SECURITY__BAD_SSO_TOKEN = PropertyKeyFactory.valueOf("SECURITY__BAD_SSO_TOKEN");
    public static final IPropertyKey SECURITY__BAD_IP_ADDRESS = PropertyKeyFactory.valueOf("SECURITY__BAD_IP_ADDRESS");
    public static final IPropertyKey SECURITY__BAD_IP_ADDRESS_PREFIX = PropertyKeyFactory.valueOf("SECURITY__BAD_IP_ADDRESS_PREFIX");
    public static final IPropertyKey SECURITY__BAD_IP_ADDRESS_ORDER = PropertyKeyFactory.valueOf("SECURITY__BAD_IP_ADDRESS_ORDER");
    public static final IPropertyKey SECURITY__FORBIDDEN_IP_ADDRESS = PropertyKeyFactory.valueOf("SECURITY__FORBIDDEN_IP_ADDRESS");
    public static final IPropertyKey SECURITY__ROLES_REMOVED = PropertyKeyFactory.valueOf("SECURITY__ROLES_REMOVED");
    public static final IPropertyKey SECURITY__ROLES_REMOVED_INFO = PropertyKeyFactory.valueOf("SECURITY__ROLES_REMOVED_INFO");
    public static final IPropertyKey SECURITY__SUPER_ADMIN = PropertyKeyFactory.valueOf("SECURITY__SUPER_ADMIN");

}
