package com.zpmc.ztos.infra.base.business.interfaces;

import com.zpmc.ztos.infra.base.business.model.MetafieldIdFactory;

public interface ISystemField {
    public static final IMetafieldId NODECFG_GKEY = MetafieldIdFactory.valueOf("nodecfgGkey");
    public static final IMetafieldId NODECFG_NODE_NAME = MetafieldIdFactory.valueOf("nodecfgNodeName");
    public static final IMetafieldId NODECFG_NODE_I_P_ADDRESS = MetafieldIdFactory.valueOf("nodecfgNodeIPAddress");
    public static final IMetafieldId NODECFG_NODE_U_R_L = MetafieldIdFactory.valueOf("nodecfgNodeURL");
    public static final IMetafieldId NODECFG_LAST_STARTUP_TIME = MetafieldIdFactory.valueOf("nodecfgLastStartupTime");
    public static final IMetafieldId NODECFG_LAST_SHUTDOWN_TIME = MetafieldIdFactory.valueOf("nodecfgLastShutdownTime");
    public static final IMetafieldId NODECFG_LOG_DIR_PATH = MetafieldIdFactory.valueOf("nodecfgLogDirPath");
    public static final IMetafieldId NODECFG_LOG_FILE_NAME_PATTERN = MetafieldIdFactory.valueOf("nodecfgLogFileNamePattern");
    public static final IMetafieldId NODECFG_SERVER_MODE = MetafieldIdFactory.valueOf("nodecfgServerMode");
    public static final IMetafieldId NODECFG_STATUS = MetafieldIdFactory.valueOf("nodecfgStatus");
    public static final IMetafieldId NODECFG_DESCRIPTION = MetafieldIdFactory.valueOf("nodecfgDescription");
    public static final IMetafieldId NODECFG_NOTE = MetafieldIdFactory.valueOf("nodecfgNote");
    public static final IMetafieldId NODECFG_LAST_FAILED_ACCESS_TIME = MetafieldIdFactory.valueOf("nodecfgLastFailedAccessTime");
    public static final IMetafieldId NODECFG_LAST_FAILED_ACCESS_ERRORS = MetafieldIdFactory.valueOf("nodecfgLastFailedAccessErrors");
    public static final IMetafieldId NODECFG_STARTUP_ERRORS = MetafieldIdFactory.valueOf("nodecfgStartupErrors");
    public static final IMetafieldId NODECFG_CREATED = MetafieldIdFactory.valueOf("nodecfgCreated");
    public static final IMetafieldId NODECFG_CREATOR = MetafieldIdFactory.valueOf("nodecfgCreator");
    public static final IMetafieldId NODECFG_CHANGED = MetafieldIdFactory.valueOf("nodecfgChanged");
    public static final IMetafieldId NODECFG_CHANGER = MetafieldIdFactory.valueOf("nodecfgChanger");
    public static final IMetafieldId ESB_GKEY = MetafieldIdFactory.valueOf("esbGkey");
    public static final IMetafieldId ESB_CONFIG_TYPE = MetafieldIdFactory.valueOf("esbConfigType");
    public static final IMetafieldId ESB_ENABLED = MetafieldIdFactory.valueOf("esbEnabled");
    public static final IMetafieldId ESB_CONFIG_NAME = MetafieldIdFactory.valueOf("esbConfigName");
    public static final IMetafieldId ESB_CONFIG_XML = MetafieldIdFactory.valueOf("esbConfigXml");
    public static final IMetafieldId ESB_CHANGED = MetafieldIdFactory.valueOf("esbChanged");
    public static final IMetafieldId ESB_CHANGER = MetafieldIdFactory.valueOf("esbChanger");
    public static final IMetafieldId ESB_CREATED = MetafieldIdFactory.valueOf("esbCreated");
    public static final IMetafieldId ESB_CREATOR = MetafieldIdFactory.valueOf("esbCreator");
    public static final IMetafieldId CLUSTER_SERVICE_GKEY = MetafieldIdFactory.valueOf("clusterServiceGkey");
    public static final IMetafieldId CLUSTER_SERVICE_KEY = MetafieldIdFactory.valueOf("clusterServiceKey");
    public static final IMetafieldId CLUSTER_SERVICE_SCOPE_LEVEL = MetafieldIdFactory.valueOf("clusterServiceScopeLevel");
    public static final IMetafieldId CLUSTER_SERVICE_SCOPE_GKEY = MetafieldIdFactory.valueOf("clusterServiceScopeGkey");
    public static final IMetafieldId CLUSTER_SERVICE_TYPE = MetafieldIdFactory.valueOf("clusterServiceType");
    public static final IMetafieldId CLUSTER_SERVICE_NAME = MetafieldIdFactory.valueOf("clusterServiceName");
    public static final IMetafieldId CLUSTER_SERVICE_STATUS = MetafieldIdFactory.valueOf("clusterServiceStatus");
    public static final IMetafieldId CLUSTER_SERVICE_I_P_ADDRESS = MetafieldIdFactory.valueOf("clusterServiceIPAddress");
    public static final IMetafieldId CLUSTER_SERVICE_MAC_ADDRESS = MetafieldIdFactory.valueOf("clusterServiceMacAddress");
    public static final IMetafieldId CLUSTER_SERVICE_PORT = MetafieldIdFactory.valueOf("clusterServicePort");
    public static final IMetafieldId CLUSTER_SERVICE_VERSION = MetafieldIdFactory.valueOf("clusterServiceVersion");
    public static final IMetafieldId CLUSTER_SERVICE_INFO = MetafieldIdFactory.valueOf("clusterServiceInfo");
    public static final IMetafieldId CLUSTER_SERVICE_STARTUP_TIME = MetafieldIdFactory.valueOf("clusterServiceStartupTime");
    public static final IMetafieldId CLUSTER_SERVICE_HEART_BEAT_TIME = MetafieldIdFactory.valueOf("clusterServiceHeartBeatTime");
    public static final IMetafieldId CLUSTER_SERVICE_ACTIVITY_TIME = MetafieldIdFactory.valueOf("clusterServiceActivityTime");
    public static final IMetafieldId CLUSTER_SERVICE_SHUTDOWN_TIME = MetafieldIdFactory.valueOf("clusterServiceShutdownTime");
    public static final IMetafieldId CLUSTER_SERVICE_USER_NAME = MetafieldIdFactory.valueOf("clusterServiceUserName");
    public static final IMetafieldId CLUSTER_SERVICE_MEMORY_USED = MetafieldIdFactory.valueOf("clusterServiceMemoryUsed");
    public static final IMetafieldId CLUSTER_SERVICE_MEMORY_MAX = MetafieldIdFactory.valueOf("clusterServiceMemoryMax");
    public static final IMetafieldId CLUSTER_SERVICE_CPU_COUNT = MetafieldIdFactory.valueOf("clusterServiceCpuCount");
    public static final IMetafieldId CLUSTER_SERVICE_CPU_LOAD = MetafieldIdFactory.valueOf("clusterServiceCpuLoad");
    public static final IMetafieldId CLUSTER_SERVICE_GROUPS = MetafieldIdFactory.valueOf("clusterServiceGroups");
}
