package com.zpmc.ztos.infra.base.business.interfaces;

import com.zpmc.ztos.infra.base.business.model.MetafieldIdFactory;

public interface IXpscacheBizMetafield {
    public static final IMetafieldId YRDM = MetafieldIdFactory.valueOf((String)"yrdm");
    public static final IMetafieldId YRDM_YARD_CODE = MetafieldIdFactory.valueOf((String)"yrdmYardCode");
    public static final IMetafieldId YRDM_YARD_NAME = MetafieldIdFactory.valueOf((String)"yrdmYardName");
    public static final IMetafieldId YRDM_YARD_BLOCKS = MetafieldIdFactory.valueOf((String)"yrdmYardBlocks");
    public static final IMetafieldId YRDM_BIN_NAME = MetafieldIdFactory.valueOf((String)"yrdmBinName");
    public static final IMetafieldId YRDM_BIN_TYPE = MetafieldIdFactory.valueOf((String)"yrdmBinType");
    public static final IMetafieldId YRDM_BIN_BIN_NAME20 = MetafieldIdFactory.valueOf((String)"yrdmBinBinName20");
    public static final IMetafieldId YRDM_BIN_BIN_NAME40 = MetafieldIdFactory.valueOf((String)"yrdmBinBinName40");
    public static final IMetafieldId YRDM_BIN_UI_FULL_POSITION20 = MetafieldIdFactory.valueOf((String)"yrdmBinUiFullPosition20");
    public static final IMetafieldId YRDM_BIN_UI_FULL_POSITION40 = MetafieldIdFactory.valueOf((String)"yrdmBinUiFullPosition40");
    public static final IMetafieldId YRDM_LABEL_SCHEME_BIN_NAME = MetafieldIdFactory.valueOf((String)"yrdmLabelSchemeBinName");
    public static final IMetafieldId YRDM_LABEL_SCHEME_UI_FULL_POSITION = MetafieldIdFactory.valueOf((String)"yrdmLabelSchemeUiFullPosition");
    public static final IMetafieldId YRDM_LABEL_SCHEME_UI_ROW_ONLY = MetafieldIdFactory.valueOf((String)"yrdmLabelSchemeUiRowOnly");
    public static final IMetafieldId YRDM_LABEL_SCHEME_UI_COLUMN_ONLY = MetafieldIdFactory.valueOf((String)"yrdmLabelSchemeUiColumnOnly");
    public static final IMetafieldId YRDM_LABEL_SCHEME_UI_TIER_ONLY = MetafieldIdFactory.valueOf((String)"yrdmLabelSchemeUiTierOnly");
    public static final IMetafieldId YRDM_BLOCK_CODE = MetafieldIdFactory.valueOf((String)"yrdmBlockCode");
    public static final IMetafieldId YRDM_BLOCK_TYPE = MetafieldIdFactory.valueOf((String)"yrdmBlockType");
    public static final IMetafieldId YRDM_BLOCK_TEU_CAPACITY = MetafieldIdFactory.valueOf((String)"yrdmBlockTeuCapacity");
    public static final IMetafieldId YRDM_BLOCK_TRAFFIC_FLOW = MetafieldIdFactory.valueOf((String)"yrdmBlockTrafficFlow");
    public static final IMetafieldId YRDM_BLOCK_FIRST_ROW = MetafieldIdFactory.valueOf((String)"yrdmBlockFirstRow");
    public static final IMetafieldId YRDM_BLOCK_LAST_ROW = MetafieldIdFactory.valueOf((String)"yrdmBlockLastRow");
    public static final IMetafieldId YRDM_BLOCK_MAX_HEIGHT = MetafieldIdFactory.valueOf((String)"yrdmBlockMaxHeight");
    public static final IMetafieldId YRDM_BLOCK_MAX_WEIGHT = MetafieldIdFactory.valueOf((String)"yrdmBlockMaxWeight");
    public static final IMetafieldId YRDM_BLOCK_TIER_COUNT = MetafieldIdFactory.valueOf((String)"yrdmBlockTierCount");
    public static final IMetafieldId YRDM_BLOCK_ROW_CONV_ID20 = MetafieldIdFactory.valueOf((String)"yrdmBlockRowConvId20");
    public static final IMetafieldId YRDM_BLOCK_ROW_CONV_ID40 = MetafieldIdFactory.valueOf((String)"yrdmBlockRowConvId40");
    public static final IMetafieldId YRDM_BLOCK_TIER_CONV_ID = MetafieldIdFactory.valueOf((String)"yrdmBlockTierConvId");
    public static final IMetafieldId YRDM_BLOCK_INVERT_X = MetafieldIdFactory.valueOf((String)"yrdmBlockInvertX");
    public static final IMetafieldId YRDM_BLOCK_INVERT_Y = MetafieldIdFactory.valueOf((String)"yrdmBlockInvertY");
    public static final IMetafieldId YRDM_BLOCK_ROTATE90 = MetafieldIdFactory.valueOf((String)"yrdmBlockRotate90");
    public static final IMetafieldId YRDM_BLOCK_ANCHOR_HORIZONTAL = MetafieldIdFactory.valueOf((String)"yrdmBlockAnchorHorizontal");
    public static final IMetafieldId YRDM_BLOCK_ANCHOR_VERTICAL = MetafieldIdFactory.valueOf((String)"yrdmBlockAnchorVertical");
    public static final IMetafieldId YRDM_BLOCK_ANGLE = MetafieldIdFactory.valueOf((String)"yrdmBlockAngle");
    public static final IMetafieldId YRDM_BLOCK_CODE_CHARS = MetafieldIdFactory.valueOf((String)"yrdmBlockCodeChars");
    public static final IMetafieldId YRDM_BLOCK_INVERT_SCAN_X = MetafieldIdFactory.valueOf((String)"yrdmBlockInvertScanX");
    public static final IMetafieldId YRDM_BLOCK_INVERT_SCAN_Y = MetafieldIdFactory.valueOf((String)"yrdmBlockInvertScanY");
    public static final IMetafieldId YRDM_BLOCK_COMPRESS_SCAN = MetafieldIdFactory.valueOf((String)"yrdmBlockCompressScan");
    public static final IMetafieldId YRDM_BLOCK_STACK_LENGTH_PIXELS = MetafieldIdFactory.valueOf((String)"yrdmBlockStackLengthPixels");
    public static final IMetafieldId YRDM_BLOCK_STACK_WIDTH_PIXELS = MetafieldIdFactory.valueOf((String)"yrdmBlockStackWidthPixels");
    public static final IMetafieldId YRDM_BLOCK_STACK_SPACE_BETWEEN_PIXELS = MetafieldIdFactory.valueOf((String)"yrdmBlockStackSpaceBetweenPixels");
    public static final IMetafieldId YRDM_BLOCK_DIRECTION = MetafieldIdFactory.valueOf((String)"yrdmBlockDirection");
    public static final IMetafieldId YRDM_BLOCK_SECTIONS = MetafieldIdFactory.valueOf((String)"yrdmBlockSections");
    public static final IMetafieldId YRDM_SECTION_NAME20 = MetafieldIdFactory.valueOf((String)"yrdmSectionName20");
    public static final IMetafieldId YRDM_SECTION_NAME40 = MetafieldIdFactory.valueOf((String)"yrdmSectionName40");
    public static final IMetafieldId YRDM_SECTION_ROW = MetafieldIdFactory.valueOf((String)"yrdmSectionRow");
    public static final IMetafieldId YRDM_SECTION_FIRST_COLUMN = MetafieldIdFactory.valueOf((String)"yrdmSectionFirstColumn");
    public static final IMetafieldId YRDM_SECTION_LAST_COLUMN = MetafieldIdFactory.valueOf((String)"yrdmSectionLastColumn");
    public static final IMetafieldId YRDM_SECTION_FIRST_TIER = MetafieldIdFactory.valueOf((String)"yrdmSectionFirstTier");
    public static final IMetafieldId YRDM_SECTION_LAST_TIER = MetafieldIdFactory.valueOf((String)"yrdmSectionLastTier");
    public static final IMetafieldId YRDM_SECTION_COLUMN_CONV_ID = MetafieldIdFactory.valueOf((String)"yrdmSectionColumnConvId");
    public static final IMetafieldId YRDM_SECTION_OTHER_COLUMN_CONV_ID = MetafieldIdFactory.valueOf((String)"yrdmSectionOtherColumnConvId");
    public static final IMetafieldId YRDM_SECTION_STACKS = MetafieldIdFactory.valueOf((String)"yrdmSectionStacks");
    public static final IMetafieldId YRDM_SECTION_ROADWAY_COLUMN = MetafieldIdFactory.valueOf((String)"yrdmSectionRoadwayColumn");
    public static final IMetafieldId YRDM_SECTION_ACCESS_BLOCKED_FIRST = MetafieldIdFactory.valueOf((String)"yrdmSectionAccessBlockedFirst");
    public static final IMetafieldId YRDM_SECTION_ACCESS_BLOCKED_LAST = MetafieldIdFactory.valueOf((String)"yrdmSectionAccessBlockedLast");
    public static final IMetafieldId YRDM_STACK_NAME20 = MetafieldIdFactory.valueOf((String)"yrdmStackName20");
    public static final IMetafieldId YRDM_STACK_NAME40 = MetafieldIdFactory.valueOf((String)"yrdmStackName40");
    public static final IMetafieldId YRDM_STACK_COLUMN = MetafieldIdFactory.valueOf((String)"yrdmStackColumn");
    public static final IMetafieldId YRDM_STACK_FIRST_TIER = MetafieldIdFactory.valueOf((String)"yrdmStackFirstTier");
    public static final IMetafieldId YRDM_STACK_LAST_TIER = MetafieldIdFactory.valueOf((String)"yrdmStackLastTier");
    public static final IMetafieldId YRDM_YARD_POINT_BLOCK_CODE = MetafieldIdFactory.valueOf((String)"yrdmYardPointBlockCode");
    public static final IMetafieldId YRDM_YARD_POINT_SEQUENCE = MetafieldIdFactory.valueOf((String)"yrdmYardPointSequence");
    public static final IMetafieldId YRDM_YARD_POINT_HORIZONTAL = MetafieldIdFactory.valueOf((String)"yrdmYardPointHorizontal");
    public static final IMetafieldId YRDM_YARD_POINT_VERTICAL = MetafieldIdFactory.valueOf((String)"yrdmYardPointVertical");
    public static final IMetafieldId CRANE_SHORT_NAME = MetafieldIdFactory.valueOf((String)"craneShortName");
    public static final IMetafieldId CRANEACTIVITY_END_TIME = MetafieldIdFactory.valueOf((String)"craneactivityEndTime");
    public static final IMetafieldId CRANEACTIVITY_START_DATE = MetafieldIdFactory.valueOf((String)"craneactivityStartDate");
    public static final IMetafieldId CRANEACTIVITY_DURATION_STRING = MetafieldIdFactory.valueOf((String)"craneactivityDurationString");

}
