package com.zpmc.ztos.infra.base.business.inventory;

import com.zpmc.ztos.infra.base.business.interfaces.*;
import com.zpmc.ztos.infra.base.business.model.MetafieldIdFactory;

public class InventoryCompoundField implements IInventoryField {
    public static final IMetafieldId UE_EQUIP_TYPE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_EQUIPMENT, (IMetafieldId) IArgoRefField.EQ_EQUIP_TYPE);
    public static final IMetafieldId UE_EQUIP_EQ_ID_FULL = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_EQUIPMENT, (IMetafieldId)IArgoRefField.EQ_ID_FULL);
    public static final IMetafieldId UE_UNIT_LINE_OP = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_UNIT, (IMetafieldId)IInventoryField.UNIT_LINE_OPERATOR);
    public static final IMetafieldId UE_UNIT_CATEGORY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_UNIT, (IMetafieldId)IInventoryField.UNIT_CATEGORY);
    public static final IMetafieldId UE_UNIT_FRT = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_UNIT, (IMetafieldId)IInventoryField.UNIT_FREIGHT_KIND);
    public static final IMetafieldId UE_UNIT_GOODS_WT_KG = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_UNIT, (IMetafieldId)IInventoryField.UNIT_GOODS_AND_CTR_WT_KG);
    public static final IMetafieldId UE_UNIT_RTG = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UE_UNIT, (IMetafieldId)IInventoryField.UNIT_ROUTING);
    public static final IMetafieldId UFV_UNIT_RTG = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_ROUTING);
    public static final IMetafieldId UFV_UNIT_GKEY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_GKEY);
    public static final IMetafieldId UFV_UNIT_LINE_OP = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_LINE_OPERATOR);
    public static final IMetafieldId UFV_UNIT_LINE_OP_LINEOP_ORDER_ITEM_NOT_UNIQUE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UFV_UNIT_LINE_OP, (IMetafieldId)IArgoRefField.LINEOP_ORDER_ITEM_NOT_UNIQUE);
    public static final IMetafieldId UFV_UNIT_FREIGHT_KIND = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_FREIGHT_KIND);
    public static final IMetafieldId UE_UNIT_RTG_DECLARED_CV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UE_UNIT_RTG, (IMetafieldId)IInventoryField.RTG_DECLARED_CV);
    public static final IMetafieldId UE_UNIT_RTG_POL = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UE_UNIT_RTG, (IMetafieldId)IInventoryField.RTG_P_O_L);
    public static final IMetafieldId UFV_UNIT_RTG_POL = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UFV_UNIT_RTG, (IMetafieldId)IInventoryField.RTG_P_O_L);
    public static final IMetafieldId UFV_UNIT_FLEX_STRING01 = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_FLEX_STRING01);
    public static final IMetafieldId UE_UNIT_RTG_POD1 = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UE_UNIT_RTG, (IMetafieldId)IInventoryField.RTG_P_O_D1);
    public static final IMetafieldId UNIT_RTG_DECLARED_CV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ROUTING, (IMetafieldId)IInventoryField.RTG_DECLARED_CV);
    public static final IMetafieldId UNIT_RTG_POL = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ROUTING, (IMetafieldId)IInventoryField.RTG_P_O_L);
    public static final IMetafieldId UNIT_RTG_POD1 = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ROUTING, (IMetafieldId)IInventoryField.RTG_P_O_D1);
    public static final IMetafieldId UNIT_UE = IInventoryField.UNIT_EQUIPMENT;
    public static final IMetafieldId UNIT_UE_EQ_ID = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_UE, (IMetafieldId)IArgoRefField.EQ_ID_FULL);
    public static final IMetafieldId UNIT_UE_EQUIP_TYPE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_UE, (IMetafieldId)IArgoRefField.EQ_EQUIP_TYPE);
    public static final IMetafieldId UNIT_GOODS_REEFREQMTS = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_GOODS, (IMetafieldId)IInventoryField.GDS_REEFER_RQMNTS);
    public static final IMetafieldId UNIT_GOODS_CMDY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_GOODS, (IMetafieldId)IInventoryField.GDS_COMMODITY);
    public static final IMetafieldId UE_UNIT_GOODS_CMDY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UE_UNIT, (IMetafieldId)UNIT_GOODS_CMDY);
    public static final IMetafieldId UNIT_GOODS_BL_NBR = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_GOODS, (IMetafieldId)IInventoryField.GDS_BL_NBR);
    public static final IMetafieldId UNIT_GOODS_REEFREQMTS_TEMP_REQ = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_GOODS_REEFREQMTS, (IMetafieldId)IInventoryField.RFREQ_TEMP_REQUIRED_C);
    public static final IMetafieldId UNIT_PAID_THRU_DAY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)UFV_PAID_THRU_DAY);
    public static final IMetafieldId UNIT_LINE_OP_ID = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_LINE_OPERATOR, (IMetafieldId)IArgoRefField.BZU_ID);
    public static final IMetafieldId UNIT_LINE_OP_GKEY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_LINE_OPERATOR, (IMetafieldId)IArgoRefField.BZU_GKEY);
    public static final IMetafieldId UNIT_LAST_KNOWN_POSITION_NAME = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UFV_LAST_KNOWN_POSITION, (IMetafieldId)POS_NAME));
    public static final IMetafieldId UNIT_LAST_KNOWN_LOC_ID = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_LAST_KNOWN_POSITION, (IMetafieldId)IInventoryField.POS_LOC_ID);
    public static final IMetafieldId UNIT_ACTIVE_IB_CV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)UFV_ACTUAL_IB_CV);
    public static final IMetafieldId UNIT_ACTIVE_OB_CV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)UFV_ACTUAL_OB_CV);
    public static final IMetafieldId UNIT_ACTIVE_IB_CV_ID = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_IB_CV, (IMetafieldId) IArgoField.CV_ID);
    public static final IMetafieldId UNIT_ACTIVE_OB_CV_ID = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_OB_CV, (IMetafieldId)IArgoField.CV_ID);
    public static final IMetafieldId UE_UNIT_GOODS_REEFREQMTS_TEMP_REQ = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UE_UNIT, (IMetafieldId)UNIT_GOODS_REEFREQMTS_TEMP_REQ);
    public static final IMetafieldId POOLEQCLASS_MEMBER_EQ_OPR = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IPoolField.POOLEQCLASS_POOL_MEMBER, (IMetafieldId)IPoolField.POOLMBR_EQ_OPER);
    public static final IMetafieldId POOLEQCLASS_MEMBER_POOL_GKEY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IPoolField.POOLEQCLASS_POOL_MEMBER, (IMetafieldId)IPoolField.POOLMBR_EQ_OPER);
    public static final IMetafieldId HZ_GOODS_PLACARD_TEXT = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.HZGOODS_PLACARD, (IMetafieldId)IInventoryField.PLACARD_TEXT);
    public static final IMetafieldId SUBSIDIARY_RISKS_PLACARD_TEXT = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.SUBRISK_PLACARD, (IMetafieldId)IInventoryField.PLACARD_TEXT);
    private static final IMetafieldId HAZARD_PLACARD_NAME = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.HZGOODS_PLACARD, (IMetafieldId)IInventoryField.PLACARD_TEXT);
    private static final IMetafieldId SUB_RISKS_PLACARD_NAME = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.SUBRISK_PLACARD, (IMetafieldId)IInventoryField.PLACARD_TEXT);
    public static final IMetafieldId UNIT_ACTIVE_FINAL_PLANNED_POSITION_SLOT = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)IInventoryBizMetafield.UFV_POSITION_PLANNED_FINAL_POS_SLOT);
    public static final IMetafieldId UNIT_ACTIVE_UFV_CAS_UNIT_REFERENCE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)IInventoryField.UFV_CAS_UNIT_REFERENCE);
    public static final IMetafieldId WI_UYV_UFV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId) IMovesField.WI_UYV, (IMetafieldId)IInventoryField.UYV_UFV);
    public static final IMetafieldId UNIT_WI_UYV_UFV = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)WI_UYV_UFV, (IMetafieldId)UnitField.UFV_UNIT);
    public static final IMetafieldId WI_UYV_UFV_UNIT_UE_UEEQUIP = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_WI_UYV_UFV, (IMetafieldId)IInventoryField.UE_EQUIPMENT);
    public static final IMetafieldId WI_UYV_UFV_UNIT_UE_UEEQUIP_EQTYPE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)WI_UYV_UFV_UNIT_UE_UEEQUIP, (IMetafieldId)IArgoRefField.EQ_EQUIP_TYPE);
    public static final IMetafieldId WI_UYV_UFV_UNIT_UE_UEEQUIP_EQTYPE_BASIC_LENGTH = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)WI_UYV_UFV_UNIT_UE_UEEQUIP_EQTYPE, (IMetafieldId)IArgoRefField.EQTYP_BASIC_LENGTH);
    public static final IMetafieldId UFV_UNIT_IS_BUNDLE = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)IInventoryField.UFV_UNIT, (IMetafieldId)IInventoryField.UNIT_IS_BUNDLE);
    public static final IMetafieldId UNIT_ACTIVE_UFV_GKEY = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UNIT_ACTIVE_UFV, (IMetafieldId)IInventoryField.UFV_GKEY);
    public static final IMetafieldId UNIT_EQUIP_ISO_GROUP = MetafieldIdFactory.getCompoundMetafieldId((IMetafieldId)UnitField.UNIT_PRIMARY_EQTYPE, (IMetafieldId)IArgoRefField.EQTYP_ISO_GROUP);

}
